### PR TITLE
NumberEnhancement: Pressing Ctrl+(number between 1-9) changes the curren...

### PR DESCRIPTION
**Pull request by vikramahuja1001**
...t tab to the number.

### CODE REVIEW

**Comment by quozl** [comment]
Tested.  Has a defect; a "1" is inserted as if typed.  How to reproduce:
* patch Terminal,
* start Terminal,
* open new tab,
* press Ctrl+1,
* press Ctrl+2,
* repeat as desired.

Observe the first tab will have "1" characters added to the shell line for every key press.  Other tabs are not affected.

**Comment by quozl** [comment]
Please add "return True" before the test for key_name == 'Tab'.  I've tested this, and it fixes the defect.

**Comment by quozl** [comment]
@vikramahuja1001, ping.  It has been a month.  Will you be reworking this pull request?

@godiard, if @vikramahuja1001 does not respond, would you like me to make a pull request?

**Comment by godiard** [comment]
@quozl, honestly, this is not a feature I am desperate to include.

**Comment by vikramahuja1001** [comment]
@quozl @godiard  Sorry. Will submit it again asap

**Comment by quozl** [comment]
@godiard, no worries, i agree, i'm unlikely to use the feature, and i don't think it will be highly used.

**Comment by vikramahuja1001** [comment]
@quozl Okay then let us close it in that case.

**Pull request closed without merging**
